apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvak
  labels:
    app: kvak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvak
  template:
    metadata:
      labels:
        app: kvak
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: kvak-storage
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: kvak
          volumeMounts:
            - name: kvak-storage
              mountPath: /storage
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: kvak.settings.k8s
          envFrom:
            - secretRef:
                name: kvak-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 800Mi
              cpu: 400m
        - name: migrate
          image: kvak
          volumeMounts:
            - name: kvak-storage
              mountPath: /storage
          command:
            - python
            - manage.py
            - migrate
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: kvak.settings.k8s
          envFrom:
            - secretRef:
                name: kvak-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 800Mi
              cpu: 400m
      containers:
        - name: kvak
          image: kvak
          volumeMounts:
            - name: kvak-storage
              mountPath: /storage
          command:
            - gunicorn
            - kvak.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
            - --workers
            - "1"
            - --threads
            - "3"
            - --timeout
            - "90"
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: kvak.settings.k8s
          envFrom:
            - secretRef:
                name: kvak-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 800Mi
              cpu: 400m
        - name: kvak-nginx
          image: nginx:alpine
          volumeMounts:
            - name: kvak-storage
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 50Mi
              cpu: 50m
