apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kvak
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: kvak
    newName: rg.fr-par.scw.cloud/djnd/kvak
    newTag: '94763e066c4ac6e22fc7e1cf26680f85ac98be37'
