apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kvak
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: kvak
    newName: rg.fr-par.scw.cloud/djnd/kvak
    newTag: '054dd7b06f4f98f07ea0901d51eaecabf130eac1'
