apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kvak
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: kvak
    newName: rg.fr-par.scw.cloud/djnd/kvak
    newTag: '20fd29d60e1cb91b8c0bda6c7d1c195c63c637ce'
