volumes:
  postgres-data:

services:
  kvak:
    build: ./kvak
    working_dir: /app
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./kvak:/app:delegated,rw
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app:$PYTHONPATH
      DB_HOST: db
      DB_NAME: kvak
      DB_USERNAME: kvak
      DB_PASSWORD: changeme
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kvak
      POSTGRES_USER: kvak
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
