# Generated by Django 5.2.5 on 2025-08-20 13:36

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navigation",
                    wagtail.fields.StreamField(
                        [("page_link", 2), ("external_link", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1)]],
                                {"icon": "link", "label": "Internal link"},
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Link", "required": True},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("url", 3)]],
                                {"icon": "link", "label": "External link"},
                            ),
                        },
                        verbose_name="Navigation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Settings",
            },
        ),
    ]
