# Generated by Django 5.2.5 on 2025-08-20 16:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_genericpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_columns",
            field=wagtail.fields.StreamField(
                [("about_column", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "ol", "hr"],
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("page", 1), ("description", 2)]],
                        {"icon": "link", "label": "Internal link"},
                    ),
                },
                verbose_name="About columns",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="courses_description",
            field=models.TextField(blank=True, verbose_name="Courses description"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Introduction text"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="resources_description",
            field=models.TextField(blank=True, verbose_name="Resources description"),
        ),
    ]
