# Generated by Django 5.2.5 on 2025-08-20 16:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_about_columns_homepage_courses_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Body"),
        ),
    ]
