# Generated by Django 5.2.5 on 2025-10-22 12:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_genericpage_body"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseMaterialPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("text", wagtail.fields.RichTextField(blank=True, verbose_name="Text")),
                ("video_url", models.URLField(blank=True, verbose_name="Video URL")),
                (
                    "questions",
                    wagtail.fields.StreamField(
                        [
                            ("multiple_choice_question", 6),
                            ("one_correct_answer_question", 6),
                            ("text_answer_question", 7),
                            ("order_by_priority_question", 10),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ul", "ol"],
                                    "label": "Question text",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ul", "ol"],
                                    "label": "Explanation text",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Option text", "max_length": 255},
                            ),
                            3: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "label": "Is correct",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("option_text", 2), ("is_correct", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.ListBlock",
                                (4,),
                                {
                                    "label": "Answer options",
                                    "max_num": 10,
                                    "min_num": 2,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("question_text", 0),
                                        ("explanation_text", 1),
                                        ("answer_options", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("question_text", 0), ("explanation_text", 1)]],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("option_text", 2)]],
                                {},
                            ),
                            9: (
                                "wagtail.blocks.ListBlock",
                                (8,),
                                {
                                    "label": "Priority options",
                                    "max_num": 10,
                                    "min_num": 2,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("question_text", 0),
                                        ("explanation_text", 1),
                                        ("priority_options", 9),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Add questions for this material",
                        null=True,
                        verbose_name="Questions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CoursePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "overview",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Course overview"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CoursesListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro_text",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Introduction text"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ExcerciseCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Category description"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ExercisePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Exercise description"
                    ),
                ),
                (
                    "estimated_time",
                    models.PositiveIntegerField(
                        verbose_name="Estimated time (minutes)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="home.excercisecategorypage",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
