# Generated by Django 5.2.5 on 2025-11-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_userfinishedbasematerial_userfinishedexcercisepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="courses_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.courseslistpage",
                verbose_name="Courses page",
            ),
        ),
    ]
