# Generated by Django 5.2.5 on 2025-11-27 11:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_coursepage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiscSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggest_courses_text",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Suggest courses text"
                    ),
                ),
                (
                    "suggest_courses_text_2",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Suggest courses text 2"
                    ),
                ),
            ],
            options={
                "verbose_name": "Miscellaneous Settings",
            },
        ),
    ]
