# Generated by Django 5.2.5 on 2025-11-27 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_miscsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnsweredQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_material_page_id",
                    models.PositiveIntegerField(verbose_name="Base Material Page ID"),
                ),
                (
                    "question_id",
                    models.CharField(max_length=255, verbose_name="Question ID"),
                ),
                ("answer_data", models.JSONField(verbose_name="Answer data")),
                (
                    "answered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Answered at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answered_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
