# Generated by Django 5.2.5 on 2025-12-02 10:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_useransweredquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headersettings",
            name="navigation",
            field=wagtail.fields.StreamField(
                [("page_link", 2), ("external_link", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("page", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": True},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 0), ("url", 3)]], {}),
                },
                verbose_name="Navigation",
            ),
        ),
    ]
