# Generated by Django 6.0.1 on 2026-02-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_basematerialpage_questions"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="badge_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Badge image",
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="claim_badge_url",
            field=models.URLField(
                blank=True,
                help_text="URL where users can claim their badge after completing a course",
                verbose_name="Claim badge URL",
            ),
        ),
    ]
