# Generated by Django 6.0.1 on 2026-03-04 14:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_alter_basematerialpage_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisepage",
            name="congratulations_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text to show when this exercise is finished",
                null=True,
                verbose_name="Congratulations text",
            ),
        ),
    ]
