# Generated by Django 6.0.1 on 2026-03-05 14:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_exercisepage_congratulations_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basematerialpage",
            name="questions",
            field=wagtail.fields.StreamField(
                [
                    ("multiple_choice_question", 7),
                    ("one_correct_answer_question", 7),
                    ("text_answer_question", 8),
                    ("order_by_priority_question", 11),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "ol", "image"],
                            "label": "Question text",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ul",
                                "ol",
                                "image",
                                "embed",
                            ],
                            "label": "Explanation text",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Option text", "max_length": 255},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Option image", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Is correct", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("option_text", 2), ("option_image", 3), ("is_correct", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {"label": "Answer options", "min_num": 2},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("question_text", 0),
                                ("explanation_text", 1),
                                ("answer_options", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("question_text", 0), ("explanation_text", 1)]],
                        {},
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("option_text", 2)]], {}),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "List the options in the correct order here, users will get a random order of these options to sort!",
                            "label": "Priority options",
                            "min_num": 2,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("question_text", 0),
                                ("explanation_text", 1),
                                ("priority_options", 10),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add questions for this material",
                null=True,
                verbose_name="Questions",
            ),
        ),
    ]
