# Generated by Django 6.0.1 on 2026-04-08 10:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_alter_basematerialpage_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about_columns",
            field=wagtail.fields.StreamField(
                [("about_column", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "ol", "hr"],
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("link", 4)]],
                        {"label": "Image"},
                    ),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 5)]],
                        {"label": "Images", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("page", 1),
                                ("description", 2),
                                ("images", 6),
                            ]
                        ],
                        {"icon": "link", "label": "Internal link"},
                    ),
                },
                verbose_name="About columns",
            ),
        ),
    ]
