# Generated by Django 6.0.1 on 2026-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_resourcepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("sl", "Slovenian"),
                    ("ca", "Catalan"),
                    ("it", "Italian"),
                ],
                default="en",
                max_length=10,
                verbose_name="Course language",
            ),
        ),
    ]
