# Generated by Django 6.0.1 on 2026-06-03 12:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_coursepage_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseslistpage",
            name="intro_text_ca",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Introduction text (Catalan)"
            ),
        ),
        migrations.AddField(
            model_name="courseslistpage",
            name="intro_text_it",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Introduction text (Italian)"
            ),
        ),
        migrations.AddField(
            model_name="courseslistpage",
            name="intro_text_sl",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Introduction text (Slovenian)"
            ),
        ),
        migrations.AlterField(
            model_name="courseslistpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Introduction text (English)"
            ),
        ),
    ]
